# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {B:/AES FINAL/aes.cache/wt} [current_project]
set_property parent.project_path {B:/AES FINAL/aes.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  {B:/AES FINAL/aes.srcs/sources_1/new/add.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/addroundkey.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/affine.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/comp.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/con2.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/inv.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/inv_affine.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/inv_lastround.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/inv_mix.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/inv_mixcolumns.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/inv_rounds.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/inv_sbox.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/inv_shiftrows.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/inv_subbytes.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/invcomp.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/keyexpansion.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/mul.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/mul2.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/mul_2.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/roundkeys.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/sbox.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/square.vhd}
  {B:/AES FINAL/aes.srcs/sources_1/new/decryption.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top decryption -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef decryption.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file decryption_utilization_synth.rpt -pb decryption_utilization_synth.pb"
